import type { Metadata } from "next";
import "./globals.css";
import { UIStateProvider } from "@/context/UIStateProvider";
import DashboardLayout from "./Components/DashboardLayout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <UIStateProvider>
                    <DashboardLayout>{children}</DashboardLayout>
                </UIStateProvider>
            </body>
        </html>
    );
}
