name: Cypress Tests

on: 
   pull_request:
     branches:
       - main  # Kör Cypress på PR:er mot main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci  # Använd npm ci för snabbare installation

      - name: Start local server
        run: npm run dev &

      - name: Install wait-on
        run: npm install -g wait-on
      
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests against local
        run: npx cypress run --headless
        env:
          BASE_URL: "http://localhost:3000"

      - name: Upload Cypress failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/screenshots/
