name: Cypress Tests

on: 
   pull_request:
     branches:
       - main  # Kör Cypress på PR:er mot main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:  # Lägg till miljövariabler här
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          build: npm run build
          start: npm start
